title:            Andrew Cairns
tagline:          'Software Developer'
description:      "I Informed You Thusly"
baseurl:          /
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty
paginate:         5
paginate_path:    "/page-:num"

poole:
    word_separator: "-"
