title:            Andrew Cairns
tagline:          'Software Developer'
description:      "I Informed You Thusly"
baseurl:          /
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty
paginate:         5
exclude: [
    'public/less'
]

poole:
    word_separator: "-"
